# Generated by Django 5.1.4 on 2025-06-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Giftyo 倉庫', max_length=100, verbose_name='倉庫名')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('pref', models.CharField(max_length=50, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('address_line', models.CharField(max_length=200, verbose_name='番地以下')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
    ]
