# Generated by Django 5.2.2 on 2025-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishitem',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='wishitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='ブランド名'),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='wish_items/%Y/%m/', verbose_name='商品画像（アップロード）'),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='desired_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='希望価格'),
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
