# Generated by Django 5.2.2 on 2025-06-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_influencer_free_url1_influencer_free_url2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to=settings.AUTH_USER_MODEL, verbose_name='送信ユーザー')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='influencer.influencer', verbose_name='受信インフルエンサー')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
