# Generated by Django 5.2.2 on 2025-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='from_user',
        ),
        migrations.AddField(
            model_name='gift',
            name='sender_name',
            field=models.CharField(default='', help_text='ギフトを送った方のお名前を入力してください', max_length=100, verbose_name='送信者名'),
            preserve_default=False,
        ),
    ]
