# Generated by Django 5.2.2 on 2025-06-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_remove_gift_from_user_gift_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='宛名')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('prefecture', models.CharField(blank=True, max_length=100, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='市区町村')),
                ('building', models.CharField(blank=True, max_length=200, verbose_name='建物名・部屋番号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='influencer.influencer', verbose_name='インフルエンサー')),
            ],
        ),
    ]
