# Generated by Django 5.2.2 on 2025-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0006_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='prefecture',
            field=models.CharField(max_length=100, verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='recipient_name',
            field=models.CharField(max_length=100, verbose_name='宛名'),
        ),
    ]
