# Generated by Django 5.2.2 on 2025-06-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0008_gift_sent_date_gift_tracking_number_gift_wish_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='wish_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='influencer.wishitem', verbose_name='対象WishItem'),
        ),
    ]
