# Generated by Django 5.2.2 on 2025-06-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0009_alter_gift_wish_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='送付日'),
        ),
    ]
