# Generated by Django 5.2.2 on 2025-06-15 22:00

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0010_gift_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='wish_item',
            field=models.ForeignKey(
                to='influencer.WishItem',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gifts',
                verbose_name='対象WishItem',
                null=True,
                blank=True,
            ),
        ),
    ]
