# Generated by Django 5.2.2 on 2025-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0011_alter_gift_wish_item_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='anonymous_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='message_card_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='payment_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gift',
            name='wrapping_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gift',
            name='sender_name',
            field=models.CharField(max_length=100, verbose_name='送信者名'),
        ),
    ]
