# Generated by Django 5.2.2 on 2025-06-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0012_gift_anonymous_fee_gift_message_card_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='決済完了'),
        ),
        migrations.AddField(
            model_name='gift',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='決済日時'),
        ),
    ]
